# Generated by Django 5.0.3 on 2024-08-20 03:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pkmnstock_app', '0021_pkmnstock_price_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_power', models.DecimalField(decimal_places=2, default=20000.0, max_digits=12)),
                ('total_portfolio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.OneToOneField(on_delete=models.Model, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PkmnPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares_purchased', models.IntegerField(default=1)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pokemon', models.ForeignKey(on_delete=models.Model, related_name='portfolio', to='pkmnstock_app.pkmnstock')),
                ('portfolio', models.ForeignKey(on_delete=models.Model, to='portfolio_app.portfolio')),
            ],
        ),
    ]
