# Generated by Django 5.0.3 on 2024-08-20 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkmnstock_app', '0021_pkmnstock_price_history'),
        ('portfolio_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='pkmnportfolio',
            old_name='shares_purchased',
            new_name='shares',
        ),
        migrations.AlterField(
            model_name='pkmnportfolio',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='pkmnstock_app.pkmnstock'),
        ),
        migrations.AlterField(
            model_name='pkmnportfolio',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pkmn_in_portfolio', to='portfolio_app.portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
