# Generated by Django 5.0.3 on 2024-08-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_alter_pkmnportfolio_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkmnportfolio',
            name='shares',
            field=models.IntegerField(default=1),
        ),
    ]
