# Generated by Django 5.0.3 on 2024-08-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkmnstock_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkmnstock',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
