# Generated by Django 5.0.3 on 2024-08-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkmnstock_app', '0002_pkmnstock_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkmnstock',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pkmnstock',
            name='details',
            field=models.JSONField(default='None'),
        ),
    ]
