# Generated by Django 5.0.3 on 2024-08-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkmnstock_app', '0003_alter_pkmnstock_base_price_alter_pkmnstock_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkmnstock',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
