# Generated by Django 5.0.3 on 2024-08-14 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkmnstock_app', '0004_alter_pkmnstock_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pkmnstock',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='pkmnstock',
            name='name',
        ),
    ]
