# Generated by Django 5.0.3 on 2024-08-14 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkmnstock_app', '0006_pkmnstock_base_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pkmnstock',
            name='base_price',
        ),
    ]
