# Generated by Django 5.0.3 on 2024-08-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkmnstock_app', '0009_alter_pkmnstock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkmnstock',
            name='pokedex_id',
            field=models.IntegerField(default=0),
        ),
    ]
