# Generated by Django 5.0.3 on 2024-08-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkmnstock_app', '0010_pkmnstock_pokedex_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkmnstock',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pkmnstock',
            name='pokedex_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
