# Generated by Django 5.0.3 on 2024-08-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkmnstock_app', '0011_alter_pkmnstock_name_alter_pkmnstock_pokedex_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkmnstock',
            name='pokedex_id',
            field=models.IntegerField(unique=True),
        ),
    ]
