# Generated by Django 5.0.3 on 2024-08-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkmnstock_app', '0012_alter_pkmnstock_pokedex_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pkmnstock',
            name='details',
        ),
        migrations.AddField(
            model_name='pkmnstock',
            name='base_stats',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pkmnstock',
            name='move_count',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pkmnstock',
            name='move_name',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pkmnstock',
            name='what_type',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
