# Generated by Django 5.0.3 on 2024-08-15 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkmnstock_app', '0013_remove_pkmnstock_details_pkmnstock_base_stats_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pkmnstock',
            old_name='move_name',
            new_name='moves',
        ),
    ]
