# Generated by Django 5.0.3 on 2024-08-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkmnstock_app', '0014_rename_move_name_pkmnstock_moves'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkmnstock',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
