# Generated by Django 5.0.3 on 2024-08-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkmnstock_app', '0016_remove_pkmnstock_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkmnstock',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
