# Generated by Django 5.0.3 on 2024-08-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkmnstock_app', '0017_pkmnstock_raw_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pkmnstock',
            name='raw_data',
        ),
        migrations.AddField(
            model_name='pkmnstock',
            name='base_price',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
