# Generated by Django 5.0.3 on 2024-08-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkmnstock_app', '0018_remove_pkmnstock_raw_data_pkmnstock_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkmnstock',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
