# Generated by Django 5.0.3 on 2024-08-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkmnstock_app', '0020_pkmnstock_evolution_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkmnstock',
            name='price_history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
